server:
  port: 8120

spring:
  datasource:
    url: jdbc:mysql://localhost:5440/school-application
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  flyway:
    baseline-on-migrate : true
